### ISSUE TITLE
Document tasks

### ISSUE THREAD

**Issue by mariuscoto** [rosedu/events#33]
### Need
This is a collection of pages that describe some useful procedures:
* how to organise an event
* how to reserve a room for an event
* how to promote an event

The pages should be editable and accept markdown for easy writing.

### Deliverables
- [ ] add db schema for Pages: id, name, content, last_edited_by
- [ ] add page to manage Pages: list all, add page, edit page
- [ ] include links to Pages when adding events

**Comment by maria** [comment]
> This page offers short lists to tasks that need to be done in certain situations. E.g.:

how to organise an event
how to reserve a room for an event

this seems out of scope and not related with the TODO list.

**Comment by mariuscoto** [comment]
One referred the implementation and the other the objective. I have updated correspondingly.

**Comment by maria** [comment]
We have a wiki on GitHub were we strived to document all of these things. I think we should use that and add a link to the wiki page to the project, which can be seen by rosedu members. 

This issue and the one with doodle are reinventing the wheel, which is already built by others (and better than we can do it).

**Comment by mariuscoto** [comment]
Don't you need some different access rights to edit those wiki pages ?

**Comment by maria** [comment]
You need to be a ROSEdu member ( and this also includes people who are
supporters), hence have access to the Github organisation.

**Comment by mariuscoto** [comment]
That works for me. I have added the corresponding [page](https://github.com/rosedu/meta/wiki/Evenimente).
