### ISSUE TITLE
Model database for activities, roles, people

### ISSUE THREAD

**Issue by maria** [rosedu/events#39]
### Need

```gherkin
As a developer
I want to describe the relations between Activities, Editions, Event and People
In order to show to users our activity and members to the community
```

### Deliverables

- Describe the above entities in Mongo collections and relations
- Deliver fast answers to questions like:
  - Which activities ROSEdu has?
  - Who are the members behind ROSEdu?
  - Who are the members and their roles for a given event?
  - Which events are a part of an activity/edition?

etc.

### Solution

[Abstract]: Create two main collections: People and Events, which will hold as many information as needed in order to answer one of the questions above quickly. Quickly meaning that we should avoid joins between collections, or too many queries in the database, and adding indexes on important fields which will be used in queries and sorts.

#### Collections fields

Primary objects:

| user | event | activity |
|----|----|------|------|-----|
| _id | _id | _id | _id |
| google: {...} | ... | name: String |
| jobs: [AEdR] | activity_id: _id | description: String|
| | edition_id: _id | edition: [Edition] |

Other objects:

| AEdR | Edition |
|----|----|----|
| activity_id: String | name: String |
| edition_id: String | people: [String] |
| role: String | |

**Comment by mariuscoto** [comment]
I did some changes to the attributes naming of some objects and included the Edition object into the Activity object. We will further test the current object hierarchy and change it again if necessary.
