### ISSUE TITLE
Edition stats

### ISSUE THREAD

**Issue by mariuscoto** [rosedu/events#47]
Add some fields to store useful info about each activity edition. Some stats that we need are:
* enrolments - number of people that signed up for the event
* participants - number of people that were allowed to join the event
* prizes - number of people that won in the final
* budget - total amount of money used for that edition
* projects - number of open source projects involved
* contributions - number of total open-source contributions

In the future, we could have a /stats page and easily see how those evolved over time.

**Comment by mariuscoto** [comment]
@maria do you have any other metrics that we should track ?

**Comment by maria** [comment]
My 2 cents:

- subscribers -> enrolments
- participants - OK
- winners -> prizes
- money -> it's called budget and I wouldn't make this a public thing. This is more related with the organising part and it should stay in a google doc internally.
- projects
- contributions

**Comment by mariuscoto** [comment]
Thank you. I have updated the issue correspondingly.
